CREATE TABLE `user` (
  `USER_ID` varchar(20) NOT NULL,
  `USER_EMAIL` varchar(100) NOT NULL,
  `USER_PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USER_EMAIL_UNIQUE` (`USER_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_detail` (
  `USER_ID` varchar(20) NOT NULL,
  `USER_TEL` varchar(20) NOT NULL,
  `USER_BIRTHDAY` varchar(8) DEFAULT NULL,
  `USER_PHOTO` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
